services:
  - type: web
    name: cricket-hub-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: cricket_league
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://cricket-hub-rp86.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 473404359350-1jpjmc0g7gndo014ebhkjjbkhu9eouko.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: PORT
        value: "10000"